---
title: Browng Bag Student Seminar
subtitle: Economics Department, Western University
author: admin
date: "2023-04-08"
# theme: pulse
format: hugo-md
---

## Introduction 

Evan Sauve, Tyler Skura, and I started the Brown Bag Student Seminar at the Economics Department of Western University during the 2023 winter term. The seminar provides a forum for Ph.D. students of any year to present research in progress or research ideas in an informal and casual environment. Students receive feedback and suggestions to improve their work.

## Format and objectives

The seminar consists of short presentations 20-30 minutes long, followed by 10-15 min of questions and feedback. The meetings are held every Thursday from 12-1 p.m.
 
The seminar prioritizes providing content feedback on original work in progress or early research ideas. It provides a safe environment for students to present new ideas.

## Additional info

Currently, the seminar is open to only Western students, but it is likely to be open to any Economics Ph.D. student shortly. To participate [contact me](mailto:<hmarti33@uwo.ca>). The current schedule is listed below.

```{r}
#| echo: FALSE
#| label: schedule
#| warning: false
#| cache: TRUE
#| tbl-cap: Brown Bag Student Seminar Schedule

library(tidyverse)

googlesheets4::gs4_deauth()
schedule<- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/11NRu0Gt1XQ3pPsS6r5TzyHFtSaxBTAjQHQ2Y8JxeN3I/edit?usp=sharing", sheet= "Winter 2023", range = "A1:D11")

schedule %>%
    filter(!is.na(Name)) %>%
    kableExtra::kable()

```

<!-- ::: {.center}

[hansmartinez.com](https://hansmartinez.com)
::: -->